# Generated by Django 3.0.5 on 2020-04-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='active',
        ),
    ]
