# Generated by Django 3.0.5 on 2020-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_remove_reminder_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='lang',
            field=models.CharField(default='he', max_length=3),
        ),
    ]
